# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    Python37-Linux:
      python.version: '3.7'
      imageName: 'ubuntu-latest'
    Python37-Windows:
      python.version: '3.7'
      imageName: 'windows-latest'
    Python37-MacOS:
      python.version: '3.7'
      imageName: 'macos-latest'

pool:
  vmImage: $(imageName)

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: 'Add conda to PATH on unix'
  condition: ne(variables.imageName, 'windows-latest')

# On Hosted macOS, the agent user doesn't have ownership of Miniconda's installation directory/
# We need to take ownership if we want to update conda or install packages globally
- bash: sudo chown -R $USER $CONDA
  displayName: 'Take ownership of conda installation'
  condition: eq(variables.imageName, 'macos-latest')

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: 'Add conda to PATH on windows'
  condition: eq(variables.imageName, 'windows-latest')

- bash: |
    choco install cygwin --params="/InstallDir:$(System.Workfolder)\cygwin"
    $(System.Workfolder)\cygwin\cygwinsetup.exe -qnNdO -R "$(System.Workfolder)\cygwin" -s "http://cygwin.mirror.constant.com" -g -P gcc-fortran
    ln cygwin\\bin\\gfortran.exe $TARGET_ENV_DIR${PATHSEP}bin${PATHSEP}gfortran
  displayName: 'Install gfortran on windows'
  condition: eq(variables.imageName, 'windows-latest')

- script: conda update --yes conda
  displayName: 'Update base conda'

- bash: |
    ./scripts/install.sh -n test_env
  displayName: 'Install dependencies and package'

- bash: |
    source activate test_env
    pip install pytest pytest-azurepipelines pytest-cov
    python -m pytest -v --cov sensory_integration_time --junitxml=junit/test-results.xml --cov-report xml --cov-report term --cov-report html .
  displayName: 'pytest'
  condition: succeeded()

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: "**/test-*.xml"
    testRunTitle: "Publish test results for Python $(python.version) and OS $(imageName)"
    mergeTestResults: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage.xml"
    reportDirectory: "$(System.DefaultWorkingDirectory)/**/htmlcov"